using System;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using HoundMazePathFinder.Algorithms;
using System.Text;
using System.Drawing;

namespace HoundMazePathFinder.Tests
{
    [TestClass]
    public class HoundMazePathFinderTests
    {
        private bool[,] map;
        private SearchParameters findingParameters;

        [TestMethod]
        public void TestMethod1()
        {
        }
        private void InitializeHoundMazeMap()
        {

            StringBuilder mazeBuilder = new StringBuilder();
            mazeBuilder.Append("FFFFFFFFFFFFFFFFFFFFFFFFFFFXFXFFFXXXFFFFFFFFFFFXXXXXXXX,");
            mazeBuilder.Append("FXXXXXXXXXXXXXXXXXFFFXFXXXFXFXFFFXXXFFFFFFFFFFFXXXXXXXX,");
            mazeBuilder.Append("FFFXXXFFFFFXFFFFFXFFFXFXXXFXFXFFFXFFFFFFFFFFFFFXXXXXXXX,");
            mazeBuilder.Append("XXXXXXFXXXFXFXXXFXFFFXFXXXFXFXFFFXFXFFFFFFFFFFFXXXXXXXX,");
            mazeBuilder.Append("XXFFFFFXFXFXFXXXFXFFFXFXXXFXFFFFFXFXFFFFFFFFFFFXXXXXXXX,");
            mazeBuilder.Append("XXFXXXXXFXFXFXXXFXFFFXFXXXFXXXFFFXFXFFFFFFFFFFFXXXXXXXX,");
            mazeBuilder.Append("XXFXXXFFFFFXFXXXFFFFFXFXXXFFFFFFFXFXFFFFFFFFFFFFFFFFFFF,");
            mazeBuilder.Append("XXFXXXFXXXXXFXXXXXFFFXFXXXFFFXXXXXFXFXXXXXFXXXXXXXXXXXF,");
            mazeBuilder.Append("XXFXXXFXFFFXFXXXXXFFFXFXXXFFFXXXXXFXFXXXXXFFFFFXXXXXXXF,");
            mazeBuilder.Append("XXFXXXFXFXFXFXXXXXFFFXFXXXFFFXXXXXFXFXXXXXFXFFFXXXXXXXF,");
            mazeBuilder.Append("XXFXFXFXFXFXFXFFFXFFFXFXXXFFFXXXXXFXFFFFFXFXFFFXXXXXXXF,");
            mazeBuilder.Append("XXFXFXFXXXFXFXXXFXXXXXFXXXFFFXXXXXFXXXFXXXFXFFFXXXXXXXF,");
            mazeBuilder.Append("XXFXFFFFFFFXFXXXFFFFFFFFFXFFFXXXXXFXFFFFFXFXFFFXFFFFFFF,");
            mazeBuilder.Append("XXFXXXXXXXXXFXXXFXXXFFFFFXXXXXXXXXFXFFFFFXFXFFFXFXXXXXF,");
            mazeBuilder.Append("XXFFFFFFFFFFFXXXFFFXFFFFFXXXFFFXXXFXFFFFFXFXFFFXFXFFFFF,");
            mazeBuilder.Append("XXFXXXXXXXXXXXXXXXFXXXXXXXXXFFFXXXFXXXXXXXFXFFFXFXXXXXX,");
            mazeBuilder.Append("FFFFFXFFFFFFFFFFFFFFFFFFFFFXFFFFFFFXFFFFFFFXFFFXFXXXXXX,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFXXXXXFXFXFFFXXXFXXXXXFXXXXXFXFXXXXXX,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFFFFFFFXFXFFFXFFFFFFFFFFFXFXFXFFFFFFF,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFXXXXXXXFXXXXXFFFFFFFFFFFXFXFXXXXXXXF,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFXFFFFFFFXXXXXFFFFFFFFFFFXFXFXFFFXFFF,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFXFXXXXXXXXXXXFFFFFFFFFFFXFXFXFFFXFXX,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFFFXFFFFFFFFFFFFFFFFFFFFFXFXFFFFFXFFF,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFXFXFFFFFFFXXXFFFFFFFFFFFXFXFXXXXXXXF,");
            mazeBuilder.Append("FFFFFXFXFFFFFFFFFFFXFXFFFFFFFXFXFFFFFFFFFFFXFFFFFFFXFFF,");
            mazeBuilder.Append("XXXXFXFXFXXXXXXXXXXXFXFFFFFFFXFXXXFXFXXXXXXXFXXXXXXXFXF,");
            mazeBuilder.Append("FFFFFXFXFXFFFFFFFFFXFXFFFFFFFXFFFXFXFFFFFFFXFXFFFFFXFXF,");
            mazeBuilder.Append("XXXXFXFXFXFXXXXXXXFXXXFXXXXXFXXXFXFXFFFFFFFXFXFFFFFXFXF,");
            mazeBuilder.Append("FFFXFXFXFXFXXXXXXXFFFFFXFFFFFFFXFFFXFFFFFFFXFXFFFFFFFXF,");
            mazeBuilder.Append("FFFXFXFXXXFXXXXXXXXXXXFXFFFFFFFXXXXXFFFFFFFXFXFFFFFXXXF,");
            mazeBuilder.Append("FFFXFXFFFFFXXXXXXXXXXXFXFFFFFFFFFFFFFFFFFFFXFXFFFFFXFXF,");
            mazeBuilder.Append("FFFXFXFXXXXXXXXXXXXXXXFXFFFFFFFXXXXXFFFFFFFXFXFFFFFXFXF,");
            mazeBuilder.Append("FFFXFXFFFFFFFXFFFFFXXXFXFFFFFFFXXXXXFFFFFFFXFXFFFFFXFFF,");
            mazeBuilder.Append("FFFXFXXXXXFFFXFXXXFXXXFXFXFXXXFXXXXXXXXXFXFXXXFFFFFXFXX,");
            mazeBuilder.Append("FFFXFXXXXXFFFXFXFFFFFFFXFXFFFXFXXXXXXXXXFXFFFFFFFFFXFFF,");
            mazeBuilder.Append("FXFXFXXXXXFFFXFXXXXXXXXXFXFFFXFXXXXXXXXXFXXXXXXXXXXXXXF,");
            mazeBuilder.Append("FXFXFFFFFXFFFXFFFFFFFFFFFXFFFXFFFFFFFFFXFFFFFFFFFXFFFXF,");
            mazeBuilder.Append("FXFXXXXXFXXXXXFXXXXXXXXXXXFFFXXXXXXXXXFXFFFFFFFFFXFXXXF,");
            mazeBuilder.Append("FXFXXXXXFXFFFFFFFFFFFFFXFXFFFFFFFFFFFXFXFFFFFFFFFXFFFFF,");
            mazeBuilder.Append("XXFXXXXXFXFXFFFFFFFFFFFXFXFXXXFFFFFFFXFXXXFXFXXXXXFXXXX,");
            mazeBuilder.Append("FFFXXXXXFXFXFFFFFFFFFFFFFXFXXXFFFFFFFFFXXXFXFFFFFFFXXXX,");
            mazeBuilder.Append("FXXXXXXXFXFXFFFFFFFFFFFXXXFXXXXXXXFXXXFXXXFXXXXXXXXXXXX,");
            mazeBuilder.Append("FFFXFFFFFXFXFFFFFFFFFFFXXXFXXXXXXXFXFFFXXXFFFFFFFFFFFXX,");
            mazeBuilder.Append("FXFXFFFFFXFXFFFFFFFFFFFXXXFXXXXXXXFXFXFXXXXXXXXXXXXXFXX,");
            mazeBuilder.Append("FXFXFFFFFXFXFFFFFFFFFFFFFXFFFFFFFXFXFXFFFFFFFFFXFFFXFXX,");
            mazeBuilder.Append("FXFXFFFFFXFXFFFFFFFFFFFXFXXXXXXXFXFXXXFFFFFFFFFXFFFXFXX,");
            mazeBuilder.Append("FXFXFFFFFXFXFFFFFFFFFFFXFFFFFFFXFXFFFXFFFFFFFFFXFFFXFXX,");
            mazeBuilder.Append("FXFXFFFFFXFXXXXXXXXXXXXXFXXXFXFXFXXXFXFFFFFFFFFXFFFXFXX,");
            mazeBuilder.Append("FXFXFFFFFXFFFFFFFXXXXXFFFXXXFXFXFXXXFFFFFFFFFFFFFFFXFXX,");
            mazeBuilder.Append("FXFXXXFXXXXXXXXXFXXXXXFXXXXXFXXXFXXXXXFFFFFFFFFXFFFXFXX,");
            mazeBuilder.Append("FXFFFFFXFFFFFXXXFXXXXXFXFFFFFFFFFXXXFXFFFFFFFFFXFFFXFXX,");
            mazeBuilder.Append("FXXXXXXXFXXXFXXXFXXXXXFXFFFXFXXXXXXXFXXXXXXXXXXXXXFXFXX,");
            mazeBuilder.Append("FFFFFFFFFXFXFXXXFXXXXXFXFFFXFFFXFFFFFFFXFFFXXXXXXXFXFXX,");
            mazeBuilder.Append("FFFFFFFFFXFXFXXXFXXXXXXXFFFXXXFXFFFFFFFXFXFXXXXXXXFXFXX,");
            mazeBuilder.Append("FFFFFFFFFXFXFXXXFFFFFFFFFFFXFFFFFFFFFFFXFXFFFFFFFFFXFFF,");
            mazeBuilder.Append("FFFFFFFFFXFXFXXXXXXXXXXXFFFXXXXXFFFFFFFXFXFFFFFFFFFXFXF,");
            mazeBuilder.Append("FFFFFFFFFXFFFFFFFXXXFFFFFFFXXXXXFFFFFFFXFXFFFFFFFFFXFXF,");
            mazeBuilder.Append("FFFFFFFFFXXXXXXXFXXXFXXXFFFXXXXXXXXXXXXXFXFFFFFFFFFXFXF,");
            mazeBuilder.Append("FFFFFFFFFXFFFFFXFXXXFXXXFFFXFFFFFFFFFFFXFXFFFFFFFFFXFXF,");
            mazeBuilder.Append("FFFFFFFFFXFFFFFXFXXXFXXXFFFXFXXXXXXXXXFXFXXXXXXXFXXXXXF,");
            mazeBuilder.Append("FFFFFFFFFXFFFFFXFXXXFXXXFFFXFXFFFFFFFFFFFXFFFFFXFXXXFFF,");
            mazeBuilder.Append("FFFFFFFFFXFFFFFXFXXXFXXXXXXXFXFXXXXXXXXXXXFFFFFXFXXXFXX,");
            mazeBuilder.Append("FFFFFFFFFXFFFFFXFXXXFFFFFFFXFXFXXXXXXXXXXXFFFFFXFXXXFXX,");
            mazeBuilder.Append("XXFXXXXXFXFFFFFXFXXXXXXXXXFXFXFXXXXXXXXXXXFXXXFXFXXXFXX,");
            mazeBuilder.Append("FFFFFFFXFXFFFFFXFFFFFFFFFXFXFFFFFFFXXXXXXXFXFFFXFFFXFFF,");
            mazeBuilder.Append("FXXXXXFXFXFFFFFXXXXXXXXXFXFXFFFFFFFXXXXXXXXXFXFXXXXXXXF,");
            mazeBuilder.Append("FXXXXXFXFFFFFFFXXXXXXXXXFXFXFFFFFFFXFFFFFFFFFXFFFFFFFFF,");
            mazeBuilder.Append("FXXXXXFXXXXXFXXXXXXXXXXXFXFXFFFFFFFXFXXXXXXXXXXXXXXXXXF,");
            mazeBuilder.Append("FXXXXXFFFXFFFXXXXXXXXXXXFXFXFFFFFFFXFXFFFFFXFFFFFFFFFXF,");
            mazeBuilder.Append("FXXXXXXXFXXXXXXXXXXXXXXXFXFXFXXXXXXXFXFXXXFXFFFFFFFFFXF,");
            mazeBuilder.Append("FXFFFFFXFFFFFFFXXXXXXXXXFXFFFXXXXXXXFXFXFFFXFFFFFFFFFFF,");
            mazeBuilder.Append("FXXXFXFXXXXXXXFXXXXXXXXXFXXXXXXXXXXXFXFXXXXXXXXXFXXXXXF,");
            mazeBuilder.Append("FFFFFXFFFFFFFXFFFFFFFFFFFFFFFFFFFFFFFXFFFFFFFFFFFXXXXXF,");
            mazeBuilder.Append("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXF,");
            mazeBuilder.Append("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXF,");
            mazeBuilder.Append("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXF,");
            mazeBuilder.Append("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXF,");
            mazeBuilder.Append("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXF,");

            string[] strArray = mazeBuilder.ToString().Split(',');
            this.map = new bool[55, strArray.Length];
            for (int i = 0; i < strArray.Length; i++)
            {
                char[] strBoolean = strArray[i].ToCharArray();
                for (int j = 0; j < strBoolean.Length; j++)
                {
                    this.map[j, i] = strBoolean[j] == 'F';
                }
            }

            var startCoordinates = new Point(54, 77);
            var finishCoordinates = new Point(12, 20);
            this.findingParameters = new SearchParameters(startCoordinates, finishCoordinates, map);
        }
    }
}
